name: AA276_project
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pip:
    - torch
    - torchvision
    - torchaudio
    - einops
    - matplotlib
    - scikit-image
    - scipy
    - pandas
    - numpy
    - tqdm
    - matplotlib
    - loguru
    - jax
    - jaxlib
    - hj_reachability
    - pillow

