name: diffusion-brt
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=12.2
  - numpy>=1.24.0
  - matplotlib>=3.7.0
  - tqdm>=4.65.0
  - pip:
    - "jax[cuda12_pip]>=0.4.13"
    - "jaxlib[cuda12_pip]>=0.4.13"
    - hj-reachability>=0.1.0
    - optax>=0.1.7 