name: diffusion-brt
channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - pip
  - cudatoolkit=12.2
  - cudnn=8.9
  - numpy=1.24.3
  - matplotlib=3.7.2
  - tqdm=4.65.0
  - pip:
    - "jax[cuda12_pip]==0.4.20"
    - "jaxlib[cuda12_pip]==0.4.20"
    - hj-reachability==0.1.0
    - optax==0.1.7 